# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

customCommands:
  - command: czg
    context: files
    subprocess: true
    key: c
  - command: czg ai
    context: files
    subprocess: true
    key: C

os:
  editPreset: "vscode"
  promptToReturnFromSubprocess: false # removes "press enter to return to lazygit" popup

git:
  pullArgs: []