# https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

customCommands:
  - command: aicommit2
    context: files
    subprocess: true
    key: C
  - command: git cz
    context: files
    subprocess: true
    key: c

os:
  editPreset: "vscode"
  promptToReturnFromSubprocess: false # removes "press enter to return to lazygit" popup

git:
  pullArgs: []