customCommands:
  - command: git-cz
    context: files
    subprocess: true
    key: c

os:
  editPreset: "vscode"
  promptToReturnFromSubprocess: false # removes "press enter to return to lazygit" popup